name: MLOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mlops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run data pipeline
        run: jupyter nbconvert --to notebook --execute 1_DataPipeline/data_pipeline.ipynb

      - name: Train model
        run: jupyter nbconvert --to notebook --execute 2_ModelTraining/train.ipynb

      - name: Run tests
        run: pytest 5_CICD_Monitoring/tests/ -v
